return {
  {
    "LazyVim/LazyVim",
    opts = {
      misc = {
        dots = "",
      },
      diagnostics = {
        Error = "",
        Warn = "",
        Info = "",
        Hint = "",
      },
      icons = {
        kinds = {
          Text = " ",
          Function = " ",
          Method = " ",
          Constructor = " ",
          Field = " ",
          Variable = " ",
          Class = " ",
          Interface = " ",
          Module = " ",
          Property = " ",
          Unit = " ",
          Value = " ",
          Enum = " ",
          Keyword = " ",
          Snippet = " ",
          Color = " ",
          File = " ",
          Reference = " ",
          Folder = " ",
          EnumMember = " ",
          Constant = " ",
          Struct = " ",
          Event = " ",
          Operator = " ",
          TypeParameter = " ",
        },
      },
    },
  },
}
